### ISSUE TITLE
Unique

### ISSUE THREAD

**Issue by tspent** [treygriffith/short-mongo-id#4]
You mention at ReadMe,  "They should be reasonably unique."

Can you elaborate on this?

**Comment by treygriffith** [comment]
If you look at the implementation in https://github.com/treygriffith/short-mongo-id/blob/master/lib/objectIdToShortId.js you can see that it uses (most of) the time of creation and 3 digits of the counter.

If you are creating less than 30 IDs per second, your odds of a collision are <50%.
